Pharmacy_Project/Controllers/IncomingController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pharmacy_Project.Models;
using Pharmacy_Project.ViewModel;
using Pharmacy_Project.ViewModels;

namespace Pharmacy_Project.Controllers
{
    [Authorize]
    public class IncomingController : Controller
    {
        private readonly PharmacyContext _context;
        private readonly int pageSize = 10;

        public IncomingController(PharmacyContext context)
        {
            _context = context;
        }

        // GET: Incoming
        public async Task<IActionResult> Index(int page = 1)
        {
            IncomingsViewModel incomingsModel;
            IQueryable<Incoming> pharmacyContext = _context.Incomings.Include(i => i.Medicine);
            var count = pharmacyContext.Count();
            pharmacyContext = pharmacyContext.Skip((page - 1) * pageSize).Take(pageSize);

            incomingsModel = new IncomingsViewModel
            {
                Incomings = pharmacyContext,
                Page = new PageViewModel(count, page, pageSize)

            };

            return View(incomingsModel);
        }

        // GET: Incoming/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Incomings == null)
            {
                return NotFound();
            }

            var incoming = await _context.Incomings
                .Include(i => i.Medicine)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (incoming == null)
            {
                return NotFound();
            }

            return View(incoming);
        }

        // GET: Incoming/Create
        public IActionResult Create()
        {
            ViewData["MedicineId"] = new SelectList(_context.Medicines, "Id", "Name");
            return View();
        }

        // POST: Incoming/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MedicineId,ArrivalDate,Count,Provider,Price")] Incoming incoming)
        {
            if (ModelState.IsValid)
            {
                _context.Add(incoming);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MedicineId"] = new SelectList(_context.Medicines, "Id", "Name", incoming.MedicineId);
            return View(incoming);
        }

        // GET: Incoming/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Incomings == null)
            {
                return NotFound();
            }

            var incoming = await _context.Incomings.FindAsync(id);
            if (incoming == null)
            {
                return NotFound();
            }
            ViewData["MedicineId"] = new SelectList(_context.Medicines, "Id", "Name", incoming.MedicineId);
            return View(incoming);
        }

        // POST: Incoming/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MedicineId,ArrivalDate,Count,Provider,Price")] Incoming incoming)
        {
            if (id != incoming.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(incoming);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IncomingExists(incoming.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MedicineId"] = new SelectList(_context.Medicines, "Id", "Id", incoming.MedicineId);
            return View(incoming);
        }

        // GET: Incoming/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Incomings == null)
            {
                return NotFound();
            }

            var incoming = await _context.Incomings
                .Include(i => i.Medicine)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (incoming == null)
            {
                return NotFound();
            }

            return View(incoming);
        }

        // POST: Incoming/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Incomings == null)
            {
                return Problem("Entity set 'PharmacyContext.Incomings'  is null.");
            }
            var incoming = await _context.Incomings.FindAsync(id);
            if (incoming != null)
            {
                _context.Incomings.Remove(incoming);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IncomingExists(int id)
        {
          return (_context.Incomings?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Pharmacy_Project/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Pharmacy_Project.Models;
using Pharmacy_Project.ViewModel;

namespace Pharmacy_Project.Controllers
{


        public class RolesController : Controller
        {
            RoleManager<IdentityRole> _roleManager;
            UserManager<IdentityUser> _userManager;
            public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
            {
                _roleManager = roleManager;
                _userManager = userManager;
            }
            public IActionResult Index() => View(_roleManager.Roles.ToList());

            public IActionResult Create() => View();
            [HttpPost]
            public async Task<IActionResult> Create(string name)
            {
                if (!string.IsNullOrEmpty(name))
                {
                    IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                return View(name);
            }

            [HttpPost]
            public async Task<IActionResult> Delete(string id)
            {
                IdentityRole role = await _roleManager.FindByIdAsync(id);
                if (role != null)
                {
                    IdentityResult result = await _roleManager.DeleteAsync(role);
                }
                return RedirectToAction("Index");
            }

            public IActionResult UserList() => View(_userManager.Users.ToList());

            public async Task<IActionResult> Edit(string userId)
            {
            // получаем пользователя
                IdentityUser user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    // получем список ролей пользователя
                    var userRoles = await _userManager.GetRolesAsync(user);
                    var allRoles = _roleManager.Roles.ToList();
                    ChangeRoleViewModel model = new ChangeRoleViewModel
                    {
                        UserId = user.Id,
                        UserEmail = user.Email,
                        UserRoles = userRoles,
                        AllRoles = allRoles
                    };
                    return View(model);
                }

                return NotFound();
            }
            [HttpPost]
            public async Task<IActionResult> Edit(string userId, List<string> roles)
            {
            // получаем пользователя
                IdentityUser user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    // получем список ролей пользователя
                    var userRoles = await _userManager.GetRolesAsync(user);
                    // получаем все роли
                    var allRoles = _roleManager.Roles.ToList();
                    // получаем список ролей, которые были добавлены
                    var addedRoles = roles.Except(userRoles);
                    // получаем роли, которые были удалены
                    var removedRoles = userRoles.Except(roles);

                    await _userManager.AddToRolesAsync(user, addedRoles);

                    await _userManager.RemoveFromRolesAsync(user, removedRoles);

                    return RedirectToAction("UserList");
                }

                return NotFound();
            }
        }
    }

Pharmacy_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pharmacy_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pharmacy_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <h1>Аптека</h1>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="Index">Информация о лекарствах</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Outgoing" asp-action="Index">Расход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producer" asp-action="Index">Производители</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Disease" asp-action="Index">Болезни</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Incoming" asp-action="Index">Приход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pharmacy_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Конфилициальность</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>